task:
  id: "020"
  name: Design file structure for .sow/ directory (data layer)
  phase: design
  status: pending

  created_at: 2025-10-12T19:30:00Z

  iteration: 0
  assigned_agent: architect
  parallel: false

  references:
    - ../../../../../../docs/FILE_STRUCTURE.md
    - ../../../../../../docs/ARCHITECTURE.md
    - ../../../../../../ROADMAP.md

  files_modified: []
