version: 2

project_name: sow

before:
  hooks:
    - sh -c "cd cli && go mod download"

builds:
  - id: sow
    main: .
    binary: sow
    dir: ./cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/jmgilman/sow/cli/cmd.Version={{.Version}}
    flags:
      - -trimpath

archives:
  - id: sow-archive
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^.*?fix(\(.+\))??!?:.+$'
      order: 1
    - title: 'Performance Improvements'
      regexp: '^.*?perf(\(.+\))??!?:.+$'
      order: 2
    - title: 'Refactors'
      regexp: '^.*?refactor(\(.+\))??!?:.+$'
      order: 3
    - title: 'Other Changes'
      order: 999

brews: # For CLI tools, brews is still the correct section despite the deprecation warning
  - name: sow
    repository:
      owner: jmgilman
      name: homebrew-apps
      branch: main
      # Use SSH URL with deploy key
      git:
        url: 'git@github.com:jmgilman/homebrew-apps.git'
        private_key: '{{ .Env.HOMEBREW_TAP_PRIVATE_KEY }}'
    directory: Formula
    homepage: https://github.com/jmgilman/sow
    description: AI-powered system of work - Structured software development with AI agents
    license: MIT
    test: |
      system "#{bin}/sow", "--version"
    install: |
      bin.install "sow"

release:
  github:
    owner: jmgilman
    name: sow
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
  mode: replace
