// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"github.com/jmgilman/sow/libs/git"
	"sync"
)

// Ensure, that GitHubClientMock does implement git.GitHubClient.
// If this is not the case, regenerate this file with moq.
var _ git.GitHubClient = &GitHubClientMock{}

// GitHubClientMock is a mock implementation of git.GitHubClient.
//
//	func TestSomethingThatUsesGitHubClient(t *testing.T) {
//
//		// make and configure a mocked git.GitHubClient
//		mockedGitHubClient := &GitHubClientMock{
//			CheckAvailabilityFunc: func() error {
//				panic("mock out the CheckAvailability method")
//			},
//			CreateIssueFunc: func(title string, body string, labels []string) (*git.Issue, error) {
//				panic("mock out the CreateIssue method")
//			},
//			CreateLinkedBranchFunc: func(issueNumber int, branchName string, checkout bool) (string, error) {
//				panic("mock out the CreateLinkedBranch method")
//			},
//			CreatePullRequestFunc: func(title string, body string, draft bool) (int, string, error) {
//				panic("mock out the CreatePullRequest method")
//			},
//			GetIssueFunc: func(number int) (*git.Issue, error) {
//				panic("mock out the GetIssue method")
//			},
//			GetLinkedBranchesFunc: func(number int) ([]git.LinkedBranch, error) {
//				panic("mock out the GetLinkedBranches method")
//			},
//			ListIssuesFunc: func(label string, state string) ([]git.Issue, error) {
//				panic("mock out the ListIssues method")
//			},
//			MarkPullRequestReadyFunc: func(number int) error {
//				panic("mock out the MarkPullRequestReady method")
//			},
//			UpdatePullRequestFunc: func(number int, title string, body string) error {
//				panic("mock out the UpdatePullRequest method")
//			},
//		}
//
//		// use mockedGitHubClient in code that requires git.GitHubClient
//		// and then make assertions.
//
//	}
type GitHubClientMock struct {
	// CheckAvailabilityFunc mocks the CheckAvailability method.
	CheckAvailabilityFunc func() error

	// CreateIssueFunc mocks the CreateIssue method.
	CreateIssueFunc func(title string, body string, labels []string) (*git.Issue, error)

	// CreateLinkedBranchFunc mocks the CreateLinkedBranch method.
	CreateLinkedBranchFunc func(issueNumber int, branchName string, checkout bool) (string, error)

	// CreatePullRequestFunc mocks the CreatePullRequest method.
	CreatePullRequestFunc func(title string, body string, draft bool) (int, string, error)

	// GetIssueFunc mocks the GetIssue method.
	GetIssueFunc func(number int) (*git.Issue, error)

	// GetLinkedBranchesFunc mocks the GetLinkedBranches method.
	GetLinkedBranchesFunc func(number int) ([]git.LinkedBranch, error)

	// ListIssuesFunc mocks the ListIssues method.
	ListIssuesFunc func(label string, state string) ([]git.Issue, error)

	// MarkPullRequestReadyFunc mocks the MarkPullRequestReady method.
	MarkPullRequestReadyFunc func(number int) error

	// UpdatePullRequestFunc mocks the UpdatePullRequest method.
	UpdatePullRequestFunc func(number int, title string, body string) error

	// calls tracks calls to the methods.
	calls struct {
		// CheckAvailability holds details about calls to the CheckAvailability method.
		CheckAvailability []struct {
		}
		// CreateIssue holds details about calls to the CreateIssue method.
		CreateIssue []struct {
			// Title is the title argument value.
			Title string
			// Body is the body argument value.
			Body string
			// Labels is the labels argument value.
			Labels []string
		}
		// CreateLinkedBranch holds details about calls to the CreateLinkedBranch method.
		CreateLinkedBranch []struct {
			// IssueNumber is the issueNumber argument value.
			IssueNumber int
			// BranchName is the branchName argument value.
			BranchName string
			// Checkout is the checkout argument value.
			Checkout bool
		}
		// CreatePullRequest holds details about calls to the CreatePullRequest method.
		CreatePullRequest []struct {
			// Title is the title argument value.
			Title string
			// Body is the body argument value.
			Body string
			// Draft is the draft argument value.
			Draft bool
		}
		// GetIssue holds details about calls to the GetIssue method.
		GetIssue []struct {
			// Number is the number argument value.
			Number int
		}
		// GetLinkedBranches holds details about calls to the GetLinkedBranches method.
		GetLinkedBranches []struct {
			// Number is the number argument value.
			Number int
		}
		// ListIssues holds details about calls to the ListIssues method.
		ListIssues []struct {
			// Label is the label argument value.
			Label string
			// State is the state argument value.
			State string
		}
		// MarkPullRequestReady holds details about calls to the MarkPullRequestReady method.
		MarkPullRequestReady []struct {
			// Number is the number argument value.
			Number int
		}
		// UpdatePullRequest holds details about calls to the UpdatePullRequest method.
		UpdatePullRequest []struct {
			// Number is the number argument value.
			Number int
			// Title is the title argument value.
			Title string
			// Body is the body argument value.
			Body string
		}
	}
	lockCheckAvailability    sync.RWMutex
	lockCreateIssue          sync.RWMutex
	lockCreateLinkedBranch   sync.RWMutex
	lockCreatePullRequest    sync.RWMutex
	lockGetIssue             sync.RWMutex
	lockGetLinkedBranches    sync.RWMutex
	lockListIssues           sync.RWMutex
	lockMarkPullRequestReady sync.RWMutex
	lockUpdatePullRequest    sync.RWMutex
}

// CheckAvailability calls CheckAvailabilityFunc.
func (mock *GitHubClientMock) CheckAvailability() error {
	if mock.CheckAvailabilityFunc == nil {
		panic("GitHubClientMock.CheckAvailabilityFunc: method is nil but GitHubClient.CheckAvailability was just called")
	}
	callInfo := struct {
	}{}
	mock.lockCheckAvailability.Lock()
	mock.calls.CheckAvailability = append(mock.calls.CheckAvailability, callInfo)
	mock.lockCheckAvailability.Unlock()
	return mock.CheckAvailabilityFunc()
}

// CheckAvailabilityCalls gets all the calls that were made to CheckAvailability.
// Check the length with:
//
//	len(mockedGitHubClient.CheckAvailabilityCalls())
func (mock *GitHubClientMock) CheckAvailabilityCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockCheckAvailability.RLock()
	calls = mock.calls.CheckAvailability
	mock.lockCheckAvailability.RUnlock()
	return calls
}

// CreateIssue calls CreateIssueFunc.
func (mock *GitHubClientMock) CreateIssue(title string, body string, labels []string) (*git.Issue, error) {
	if mock.CreateIssueFunc == nil {
		panic("GitHubClientMock.CreateIssueFunc: method is nil but GitHubClient.CreateIssue was just called")
	}
	callInfo := struct {
		Title  string
		Body   string
		Labels []string
	}{
		Title:  title,
		Body:   body,
		Labels: labels,
	}
	mock.lockCreateIssue.Lock()
	mock.calls.CreateIssue = append(mock.calls.CreateIssue, callInfo)
	mock.lockCreateIssue.Unlock()
	return mock.CreateIssueFunc(title, body, labels)
}

// CreateIssueCalls gets all the calls that were made to CreateIssue.
// Check the length with:
//
//	len(mockedGitHubClient.CreateIssueCalls())
func (mock *GitHubClientMock) CreateIssueCalls() []struct {
	Title  string
	Body   string
	Labels []string
} {
	var calls []struct {
		Title  string
		Body   string
		Labels []string
	}
	mock.lockCreateIssue.RLock()
	calls = mock.calls.CreateIssue
	mock.lockCreateIssue.RUnlock()
	return calls
}

// CreateLinkedBranch calls CreateLinkedBranchFunc.
func (mock *GitHubClientMock) CreateLinkedBranch(issueNumber int, branchName string, checkout bool) (string, error) {
	if mock.CreateLinkedBranchFunc == nil {
		panic("GitHubClientMock.CreateLinkedBranchFunc: method is nil but GitHubClient.CreateLinkedBranch was just called")
	}
	callInfo := struct {
		IssueNumber int
		BranchName  string
		Checkout    bool
	}{
		IssueNumber: issueNumber,
		BranchName:  branchName,
		Checkout:    checkout,
	}
	mock.lockCreateLinkedBranch.Lock()
	mock.calls.CreateLinkedBranch = append(mock.calls.CreateLinkedBranch, callInfo)
	mock.lockCreateLinkedBranch.Unlock()
	return mock.CreateLinkedBranchFunc(issueNumber, branchName, checkout)
}

// CreateLinkedBranchCalls gets all the calls that were made to CreateLinkedBranch.
// Check the length with:
//
//	len(mockedGitHubClient.CreateLinkedBranchCalls())
func (mock *GitHubClientMock) CreateLinkedBranchCalls() []struct {
	IssueNumber int
	BranchName  string
	Checkout    bool
} {
	var calls []struct {
		IssueNumber int
		BranchName  string
		Checkout    bool
	}
	mock.lockCreateLinkedBranch.RLock()
	calls = mock.calls.CreateLinkedBranch
	mock.lockCreateLinkedBranch.RUnlock()
	return calls
}

// CreatePullRequest calls CreatePullRequestFunc.
func (mock *GitHubClientMock) CreatePullRequest(title string, body string, draft bool) (int, string, error) {
	if mock.CreatePullRequestFunc == nil {
		panic("GitHubClientMock.CreatePullRequestFunc: method is nil but GitHubClient.CreatePullRequest was just called")
	}
	callInfo := struct {
		Title string
		Body  string
		Draft bool
	}{
		Title: title,
		Body:  body,
		Draft: draft,
	}
	mock.lockCreatePullRequest.Lock()
	mock.calls.CreatePullRequest = append(mock.calls.CreatePullRequest, callInfo)
	mock.lockCreatePullRequest.Unlock()
	return mock.CreatePullRequestFunc(title, body, draft)
}

// CreatePullRequestCalls gets all the calls that were made to CreatePullRequest.
// Check the length with:
//
//	len(mockedGitHubClient.CreatePullRequestCalls())
func (mock *GitHubClientMock) CreatePullRequestCalls() []struct {
	Title string
	Body  string
	Draft bool
} {
	var calls []struct {
		Title string
		Body  string
		Draft bool
	}
	mock.lockCreatePullRequest.RLock()
	calls = mock.calls.CreatePullRequest
	mock.lockCreatePullRequest.RUnlock()
	return calls
}

// GetIssue calls GetIssueFunc.
func (mock *GitHubClientMock) GetIssue(number int) (*git.Issue, error) {
	if mock.GetIssueFunc == nil {
		panic("GitHubClientMock.GetIssueFunc: method is nil but GitHubClient.GetIssue was just called")
	}
	callInfo := struct {
		Number int
	}{
		Number: number,
	}
	mock.lockGetIssue.Lock()
	mock.calls.GetIssue = append(mock.calls.GetIssue, callInfo)
	mock.lockGetIssue.Unlock()
	return mock.GetIssueFunc(number)
}

// GetIssueCalls gets all the calls that were made to GetIssue.
// Check the length with:
//
//	len(mockedGitHubClient.GetIssueCalls())
func (mock *GitHubClientMock) GetIssueCalls() []struct {
	Number int
} {
	var calls []struct {
		Number int
	}
	mock.lockGetIssue.RLock()
	calls = mock.calls.GetIssue
	mock.lockGetIssue.RUnlock()
	return calls
}

// GetLinkedBranches calls GetLinkedBranchesFunc.
func (mock *GitHubClientMock) GetLinkedBranches(number int) ([]git.LinkedBranch, error) {
	if mock.GetLinkedBranchesFunc == nil {
		panic("GitHubClientMock.GetLinkedBranchesFunc: method is nil but GitHubClient.GetLinkedBranches was just called")
	}
	callInfo := struct {
		Number int
	}{
		Number: number,
	}
	mock.lockGetLinkedBranches.Lock()
	mock.calls.GetLinkedBranches = append(mock.calls.GetLinkedBranches, callInfo)
	mock.lockGetLinkedBranches.Unlock()
	return mock.GetLinkedBranchesFunc(number)
}

// GetLinkedBranchesCalls gets all the calls that were made to GetLinkedBranches.
// Check the length with:
//
//	len(mockedGitHubClient.GetLinkedBranchesCalls())
func (mock *GitHubClientMock) GetLinkedBranchesCalls() []struct {
	Number int
} {
	var calls []struct {
		Number int
	}
	mock.lockGetLinkedBranches.RLock()
	calls = mock.calls.GetLinkedBranches
	mock.lockGetLinkedBranches.RUnlock()
	return calls
}

// ListIssues calls ListIssuesFunc.
func (mock *GitHubClientMock) ListIssues(label string, state string) ([]git.Issue, error) {
	if mock.ListIssuesFunc == nil {
		panic("GitHubClientMock.ListIssuesFunc: method is nil but GitHubClient.ListIssues was just called")
	}
	callInfo := struct {
		Label string
		State string
	}{
		Label: label,
		State: state,
	}
	mock.lockListIssues.Lock()
	mock.calls.ListIssues = append(mock.calls.ListIssues, callInfo)
	mock.lockListIssues.Unlock()
	return mock.ListIssuesFunc(label, state)
}

// ListIssuesCalls gets all the calls that were made to ListIssues.
// Check the length with:
//
//	len(mockedGitHubClient.ListIssuesCalls())
func (mock *GitHubClientMock) ListIssuesCalls() []struct {
	Label string
	State string
} {
	var calls []struct {
		Label string
		State string
	}
	mock.lockListIssues.RLock()
	calls = mock.calls.ListIssues
	mock.lockListIssues.RUnlock()
	return calls
}

// MarkPullRequestReady calls MarkPullRequestReadyFunc.
func (mock *GitHubClientMock) MarkPullRequestReady(number int) error {
	if mock.MarkPullRequestReadyFunc == nil {
		panic("GitHubClientMock.MarkPullRequestReadyFunc: method is nil but GitHubClient.MarkPullRequestReady was just called")
	}
	callInfo := struct {
		Number int
	}{
		Number: number,
	}
	mock.lockMarkPullRequestReady.Lock()
	mock.calls.MarkPullRequestReady = append(mock.calls.MarkPullRequestReady, callInfo)
	mock.lockMarkPullRequestReady.Unlock()
	return mock.MarkPullRequestReadyFunc(number)
}

// MarkPullRequestReadyCalls gets all the calls that were made to MarkPullRequestReady.
// Check the length with:
//
//	len(mockedGitHubClient.MarkPullRequestReadyCalls())
func (mock *GitHubClientMock) MarkPullRequestReadyCalls() []struct {
	Number int
} {
	var calls []struct {
		Number int
	}
	mock.lockMarkPullRequestReady.RLock()
	calls = mock.calls.MarkPullRequestReady
	mock.lockMarkPullRequestReady.RUnlock()
	return calls
}

// UpdatePullRequest calls UpdatePullRequestFunc.
func (mock *GitHubClientMock) UpdatePullRequest(number int, title string, body string) error {
	if mock.UpdatePullRequestFunc == nil {
		panic("GitHubClientMock.UpdatePullRequestFunc: method is nil but GitHubClient.UpdatePullRequest was just called")
	}
	callInfo := struct {
		Number int
		Title  string
		Body   string
	}{
		Number: number,
		Title:  title,
		Body:   body,
	}
	mock.lockUpdatePullRequest.Lock()
	mock.calls.UpdatePullRequest = append(mock.calls.UpdatePullRequest, callInfo)
	mock.lockUpdatePullRequest.Unlock()
	return mock.UpdatePullRequestFunc(number, title, body)
}

// UpdatePullRequestCalls gets all the calls that were made to UpdatePullRequest.
// Check the length with:
//
//	len(mockedGitHubClient.UpdatePullRequestCalls())
func (mock *GitHubClientMock) UpdatePullRequestCalls() []struct {
	Number int
	Title  string
	Body   string
} {
	var calls []struct {
		Number int
		Title  string
		Body   string
	}
	mock.lockUpdatePullRequest.RLock()
	calls = mock.calls.UpdatePullRequest
	mock.lockUpdatePullRequest.RUnlock()
	return calls
}
