// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package schemas

import (
	"time"
)

// ProjectState defines the schema for .sow/project/state.yaml
//
// This file tracks the state of an active project across all 5 phases.
// All projects have the same 5 phases; the 'enabled' flag controls
// which phases actually execute.
type ProjectState struct {
	// Project metadata
	Project struct {
		// Kebab-case project identifier
		Name string `json:"name"`

		// Git branch name this project belongs to
		Branch string `json:"branch"`

		// Human-readable project description
		Description string `json:"description"`

		// ISO 8601 timestamps
		Created_at time.Time `json:"created_at"`

		Updated_at time.Time `json:"updated_at"`
	} `json:"project"`

	// 5-phase structure (fixed phases, enabled flag controls execution)
	Phases struct {
		// Phase 1: Discovery (optional, human-led)
		Discovery DiscoveryPhase `json:"discovery"`

		// Phase 2: Design (optional, human-led)
		Design DesignPhase `json:"design"`

		// Phase 3: Implementation (required, AI-autonomous)
		Implementation ImplementationPhase `json:"implementation"`

		// Phase 4: Review (required, AI-autonomous)
		Review ReviewPhase `json:"review"`

		// Phase 5: Finalize (required, AI-autonomous)
		Finalize FinalizePhase `json:"finalize"`
	} `json:"phases"`
}

// Phase represents common phase fields
type Phase struct {
	// Phase execution status
	Status string `json:"status"`

	// Timestamps
	Created_at time.Time `json:"created_at"`

	Started_at any/* CUE disjunction: (null|string) */ `json:"started_at"`

	Completed_at any/* CUE disjunction: (null|string) */ `json:"completed_at"`
}

// DiscoveryPhase represents the discovery phase
type DiscoveryPhase struct {
	// Phase execution status
	Status string `json:"status"`

	// Timestamps
	Created_at time.Time `json:"created_at"`

	Started_at any/* CUE disjunction: (null|string) */ `json:"started_at"`

	Completed_at any/* CUE disjunction: (null|string) */ `json:"completed_at"`

	// Can be disabled
	Enabled bool `json:"enabled"`

	// Discovery type categorization
	Discovery_type any/* CUE disjunction: (null|string) */ `json:"discovery_type"`

	// Discovery artifacts requiring approval
	Artifacts []Artifact `json:"artifacts"`
}

// DesignPhase represents the design phase
type DesignPhase struct {
	// Phase execution status
	Status string `json:"status"`

	// Timestamps
	Created_at time.Time `json:"created_at"`

	Started_at any/* CUE disjunction: (null|string) */ `json:"started_at"`

	Completed_at any/* CUE disjunction: (null|string) */ `json:"completed_at"`

	// Can be disabled
	Enabled bool `json:"enabled"`

	// Whether architect agent was used
	Architect_used any/* CUE disjunction: (null|bool) */ `json:"architect_used"`

	// Design artifacts requiring approval (ADRs, design docs)
	Artifacts []Artifact `json:"artifacts"`
}

// ImplementationPhase represents the implementation phase
type ImplementationPhase struct {
	// Phase execution status
	Status string `json:"status"`

	// Timestamps
	Created_at time.Time `json:"created_at"`

	Started_at any/* CUE disjunction: (null|string) */ `json:"started_at"`

	Completed_at any/* CUE disjunction: (null|string) */ `json:"completed_at"`

	// Always enabled
	Enabled bool `json:"enabled"`

	// Whether planner agent was used
	Planner_used any/* CUE disjunction: (null|bool) */ `json:"planner_used"`

	// Approved task list (gap-numbered)
	Tasks []Task `json:"tasks"`

	// Tasks awaiting human approval before execution
	Pending_task_additions any/* CUE disjunction: (null|list) */ `json:"pending_task_additions"`
}

// RefsCacheIndex defines the schema for ~/.cache/sow/index.json
//
// This is the cache index containing transient metadata about cached
// references. Stored per-machine, not committed to git.
type RefsCacheIndex struct {
	// Schema version (semantic versioning)
	Version string `json:"version"`

	// Cached reference metadata
	Refs []CachedRef `json:"refs"`
}

// CachedRef represents a cached reference
type CachedRef struct {
	// Reference ID (matches ID from committed or local index)
	Id string `json:"id"`

	// Type inferred from source URL (stored for quick lookup)
	Type string `json:"type"`

	// Absolute cache path (e.g., /Users/josh/.cache/sow/refs/git/abc123/)
	Cache_path string `json:"cache_path"`

	// Last updated timestamp
	Last_updated time.Time `json:"last_updated"`

	// Repositories using this cached ref
	Used_by []CacheUsage `json:"used_by"`

	// Type-specific metadata
	Metadata CacheMetadata `json:"metadata"`
}

// CacheMetadata is polymorphic based on type
type CacheMetadata struct {
	// Git type metadata
	Git *GitMetadata `json:"git,omitempty"`

	// File type metadata
	File *FileMetadata `json:"file,omitempty"`
}

// GitMetadata contains git-specific cache data
type GitMetadata struct {
	// Current local commit SHA
	Commit_sha string `json:"commit_sha"`

	// Latest remote commit SHA (updated on status check)
	Remote_sha string `json:"remote_sha,omitempty"`

	// Last time remote was checked
	Last_checked time.Time `json:"last_checked,omitempty"`

	// Staleness status
	Status string `json:"status"`

	// Number of commits behind remote (0 if current)
	Commits_behind int64 `json:"commits_behind"`
}

// FileMetadata contains file-specific cache data
type FileMetadata struct {
}

// CacheUsage represents a repository using this cached ref
type CacheUsage struct {
	// Absolute path to consuming repository
	Repo_path string `json:"repo_path"`

	// How the cache is linked (symlink on Unix, copy on Windows)
	Link_type string `json:"link_type"`

	// Link name in the consuming repo's .sow/refs/ directory
	Link_name string `json:"link_name"`
}

// RefsCommittedIndex defines the schema for .sow/refs/index.json
//
// This is the committed index containing categorical metadata about
// refs, shared with the team via git. Contains configuration
// but not transient data like SHAs or timestamps.
type RefsCommittedIndex struct {
	// Schema version (semantic versioning)
	Version string `json:"version"`

	// Reference definitions
	Refs []Ref `json:"refs"`
}

// Ref represents a reference to external content
type Ref struct {
	// Unique identifier (auto-generated)
	Id string `json:"id"`

	// Source URL with scheme that determines type
	// Examples:
	//   - git+https://github.com/org/repo
	//   - git+ssh://git@github.com/org/repo
	//   - git@github.com:org/repo (auto-converted to git+ssh://)
	//   - file:///absolute/path
	Source string `json:"source"`

	// Semantic type (what the content represents)
	Semantic string `json:"semantic"`

	// Symlink name in .sow/refs/
	Link string `json:"link"`

	// Topic keywords for categorization
	Tags []string `json:"tags"`

	// One-sentence description
	Description string `json:"description"`

	// 2-3 sentence summary (optional)
	Summary string `json:"summary"`

	// Type-specific configuration
	// Structure depends on URL scheme
	Config RefConfig `json:"config"`
}

// RefConfig is a polymorphic config structure
// Validation depends on the source URL scheme
type RefConfig struct {
	// Git type config (for git+https://, git+ssh://, git@ URLs)
	// Branch name (optional, defaults to repo default)
	Branch string `json:"branch,omitempty"`

	// Subpath within repository (optional, defaults to root)
	// Use "" or omit for root
	//
	// Future type configs would be added here
	// For example, web type:
	// scrape_depth?: int & >=1
	// follow_links?: bool
	Path string `json:"path,omitempty"`
}

// RefsLocalIndex defines the schema for .sow/refs/index.local.json
//
// This is the local-only index for references that should not be
// shared with the team (e.g., work-in-progress docs, personal notes).
// This file is git-ignored.
//
// Note: File refs are typically added as local refs since they
// reference paths on the local machine.
type RefsLocalIndex struct {
	// Schema version (semantic versioning)
	Version string `json:"version"`

	// Local reference definitions
	// Uses same structure as committed refs
	Refs []Ref `json:"refs"`
}

// ReviewPhase represents the review phase
type ReviewPhase struct {
	// Phase execution status
	Status string `json:"status"`

	// Timestamps
	Created_at time.Time `json:"created_at"`

	Started_at any/* CUE disjunction: (null|string) */ `json:"started_at"`

	Completed_at any/* CUE disjunction: (null|string) */ `json:"completed_at"`

	// Always enabled
	Enabled bool `json:"enabled"`

	// Current review iteration (increments on loop-back)
	Iteration int64 `json:"iteration"`

	// Review reports (numbered 001, 002, 003...)
	Reports []ReviewReport `json:"reports"`
}

// FinalizePhase represents the finalize phase
type FinalizePhase struct {
	// Phase execution status
	Status string `json:"status"`

	// Timestamps
	Created_at time.Time `json:"created_at"`

	Started_at any/* CUE disjunction: (null|string) */ `json:"started_at"`

	Completed_at any/* CUE disjunction: (null|string) */ `json:"completed_at"`

	// Always enabled
	Enabled bool `json:"enabled"`

	// Documentation files updated
	Documentation_updates any/* CUE disjunction: (null|list) */ `json:"documentation_updates"`

	// Design artifacts moved to knowledge (from→to pairs)
	Artifacts_moved any/* CUE disjunction: (null|list) */ `json:"artifacts_moved"`

	// Critical gate: must be true before phase completion
	Project_deleted bool `json:"project_deleted"`

	// Pull request URL (created during finalize)
	Pr_url any/* CUE disjunction: (null|string) */ `json:"pr_url"`
}

// Artifact represents an artifact requiring human approval
type Artifact struct {
	// Path relative to .sow/project/
	Path string `json:"path"`

	// Human approval status
	Approved bool `json:"approved"`

	// When artifact was created
	Created_at time.Time `json:"created_at"`
}

// Task represents an implementation task
type Task struct {
	// Gap-numbered ID (010, 020, 030...)
	Id string `json:"id"`

	// Task name
	Name string `json:"name"`

	// Task status
	Status string `json:"status"`

	// Can run in parallel with other tasks
	Parallel bool `json:"parallel"`

	// Task IDs this task depends on
	Dependencies any/* CUE disjunction: (null|list) */ `json:"dependencies"`
}

// ReviewReport represents a review iteration report
type ReviewReport struct {
	// Report ID (001, 002, 003...)
	Id string `json:"id"`

	// Path relative to .sow/project/phases/review/
	Path string `json:"path"`

	// When report was created
	Created_at time.Time `json:"created_at"`

	// Review assessment
	Assessment string `json:"assessment"`
}

// TaskState defines the schema for task state files at:
// .sow/project/phases/implementation/tasks/<id>/state.yaml
//
// This tracks metadata for individual implementation tasks.
type TaskState struct {
	Task struct {
		// Task ID (matches directory name, gap-numbered)
		Id string `json:"id"`

		// Task name
		Name string `json:"name"`

		// Always "implementation" in the 5-phase model
		Phase string `json:"phase"`

		// Task execution status
		Status string `json:"status"`

		// Timestamps
		Created_at time.Time `json:"created_at"`

		Started_at any/* CUE disjunction: (null|string) */ `json:"started_at"`

		Updated_at time.Time `json:"updated_at"`

		Completed_at any/* CUE disjunction: (null|string) */ `json:"completed_at"`

		// Iteration counter (managed by orchestrator)
		// Used to construct agent ID: {assigned_agent}-{iteration}
		Iteration int64 `json:"iteration"`

		// Agent assigned to this task (e.g., "implementer", "architect")
		// Used to construct agent ID: {assigned_agent}-{iteration}
		Assigned_agent string `json:"assigned_agent"`

		// Context file paths (relative to .sow/)
		// Compiled by orchestrator during context preparation
		References []string `json:"references"`

		// Human feedback/corrections
		Feedback []Feedback `json:"feedback"`

		// Files modified during task execution
		// Auto-populated by worker via 'sow log' command
		Files_modified []string `json:"files_modified"`
	} `json:"task"`
}

// Feedback represents human corrections/guidance
type Feedback struct {
	// Feedback ID (001, 002, 003...)
	Id string `json:"id"`

	// When feedback was provided
	Created_at time.Time `json:"created_at"`

	// Feedback status
	Status string `json:"status"`
}
